@startuml sklearn
class StandardScaler {
    + fit()
    + transform()
    + fit_transform()
    + mean_
    + scale_
}

class LinearRegression{
    + fit()
    + coef_
    + intercept_
    + predict()
}
@enduml