@startuml 拿到陌生代码怎么办
enum 拿到陌生代码怎么办{
    + 快速浏览,有没有python基础语法问题
    + 看看导入了哪些库,有没有从未见过的库
    + ai一下源代码,快速了解含义
    + ai相关知识,迅速了解一下
    + 回归代码,逐步分析
    + 每理解一部分,编写成类
    + 不明白之处,迅速debug'回归上面debug问题'
    + 源代码分析完了后,回归课本,仔细参阅
    + 看完课本后,再分析源代码
    + 优化自己写好的类.
    + 最后写相关逻辑分析'也就是我目前写的'
}

@enduml